name: Build and Test
 
on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:

  test:
    strategy:
      matrix:
        node-version: [18.x]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8.6.2
          run_install: |
            - recursive: true
              args: [--no-frozen-lockfile, --strict-peer-dependencies]

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.7.0
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true

      - name: Build
        working-directory: iam
        run: pnpm build
